name: Release Binaries
on:
  push:
    tags:
      - 'v*' # Triggers whenever you push a tag starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            suffix: ""
          - goos: windows
            goarch: amd64
            suffix: ".exe"
          - goos: darwin
            goarch: arm64
            suffix: "-macos-arm"
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'
      - name: Build binaries
        run: |
          OUT_NAME="quickdo${{ matrix.suffix }}"

          VERSION_TAG="${{ github.ref_name }}"

          CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -ldflags "-X main.Version=$VERSION_TAG" -o "dist/${{ matrix.goos }}/$OUT_NAME" .
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: quickdo-*
